# 第5章 LogisticRegression
## By LiuGang - 2018/11/16
## Reference Book - statistical learning method (Chinese)

### 1:  Create some data

In [2]:
import numpy as np
X = np.array([[1,2],[2,2],[3,1],[5,-0.5],[1,1],[2,0],[0.5,1],[-1,2]])
y = np.array([1,1,1,1,0,0,0,0])

### 2: Class

In [56]:
class LogisticRegression():
    def __init__(self,X,y,lr,init_method,epoch,scope):
        self.X = X
        self.y = y
        self.lr = lr
        self.scope=scope
        self.init_method = init_method
        self.wb = np.zeros((1,self.X.shape[1]+1))
        self.epoch = epoch
    
    def get_init_wb(self):
        if self.init_method=='zero':
            return np.zeros((1,self.X.shape[1]+1))
        elif self.init_method=='rand':
            return np.random.rand(1, self.X.shape[1]+1)
        elif self.init_method=='randint':
            return np.random.randint(0, 10, size=(1, self.X.shape[1]+1))
        else:
            return init_method
        
    def update_wb(self, X, y):
        delta_w = y * X-np.dot((np.exp(np.dot(self.wb[0,0:-1], X.T)+self.wb[0,-1])/   \
                           (1 + np.exp(np.dot(self.wb[0,0:-1], X.T)+self.wb[0,-1]))), X)
        delta_b = y - np.exp(np.dot(self.wb[0,0:-1], X.T)+self.wb[0,-1])/   \
                           (1 + np.exp(np.dot(self.wb[0,0:-1], X.T)+self.wb[0,-1]))
        self.wb[0,0:-1] = self.wb[0,0:-1] + self.lr*delta_w
        self.wb[0, -1] = self.wb[0, -1] + self.lr*delta_b
        #print(self.wb)
        
    def calculate_acc(self):
        com_cou = np.exp(np.dot(self.wb[0,0:-1], X.T)+self.wb[0,-1])/   \
                           (1 + np.exp(np.dot(self.wb[0,0:-1], X.T)+self.wb[0,-1]))
        return com_cou
    
    def train(self):
        self.wb = self.get_init_wb()
        for i in range(self.epoch):
            for j in range(self.X.shape[0]):
                self.update_wb(self.X[j], y[j])
            if i%self.scope==0:
                print('epoch {} '.format(i+1),'accuracy: ',self.calculate_acc())
        print('epoch {} '.format(i+1),'accuracy: ',self.calculate_acc())
        print('-------------training finished!!!-------------')
    
    def predict_prob(self, data):
        com_cou = np.exp(np.dot(self.wb[0,0:-1], data.T)+self.wb[0,-1])/   \
                    (1 + np.exp(np.dot(self.wb[0,0:-1], data.T)+self.wb[0,-1]))
        return com_cou

In [55]:
mylr = LogisticRegression(X,y,0.5,'zero',40, 1)
mylr.train()

[[0.25 0.5  0.25]]
[[0.3980472 0.6480472 0.3240236]]
[[0.55228609 0.69946016 0.37543656]]
[[0.6973442  0.68495435 0.40444818]]
[[ 0.26908022  0.25669037 -0.02381579]]
[[-0.35674419  0.25669037 -0.336728  ]]
[[-0.46568286  0.03881304 -0.55460533]]
[[-0.21709489 -0.45836289 -0.8031933 ]]
epoch 1  accuracy:  [0.12597627 0.10394789 0.12866203 0.15983097 0.18563125 0.22489183
 0.2026031  0.18200468]
[[ 0.21991697  0.41566084 -0.36618143]]
[[ 0.50794635  0.70369021 -0.22216675]]
[[ 0.68590791  0.76301073 -0.16284623]]
[[ 0.81813454  0.74978807 -0.1364009 ]]
[[ 0.41456539  0.34621892 -0.53997005]]
[[-0.15722527  0.34621892 -0.82586538]]
[[-0.24821286  0.16424373 -1.00784056]]
[[-0.05128581 -0.22961035 -1.2047676 ]]
epoch 2  accuracy:  [0.15248089 0.14597066 0.16963231 0.20646094 0.18457346 0.21293243
 0.18846413 0.16621375]
[[ 0.37247374  0.61790876 -0.78100805]]
[[ 0.6039922   0.84942721 -0.66524882]]
[[ 0.78340302  0.90923082 -0.60544521]]
[[ 0.91921038  0.89565009 -0.57828374]]
[[ 0.531726

[[ 2.3017502   3.19438332 -7.14287829]]
[[ 2.28738697  3.16565685 -7.17160476]]
[[ 2.30837691  3.12367696 -7.1925947 ]]
epoch 40  accuracy:  [0.79626893 0.97519309 0.94563895 0.94199394 0.14672262 0.07070954
 0.05143023 0.03719711]
epoch 40  accuracy:  [0.79626893 0.97519309 0.94563895 0.94199394 0.14672262 0.07070954
 0.05143023 0.03719711]
-------------training finished!!!-------------
